spring.datasource.url=jdbc:postgresql://localhost:5432/stock-helper
spring.datasource.username=admingta
spring.datasource.password=Cosmos@1996
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
