spring.datasource.url=jdbc:postgresql://localhost:5432/stock-helper
spring.datasource.username=admingta
spring.datasource.password=Cosmos@1996
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update


#spring.datasource.url=jdbc:postgresql://dpg-cmt8rji1hbls73cp648g-a.oregon-postgres.render.com/stock_helper
#spring.datasource.username=admingta
#spring.datasource.password=3xcFuodBL93nZ6Ld1v9LUPpJbFRgR7s0
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#spring.datasource.url=jdbc:postgresql://home.cwkfpvi1usun.ap-south-1.rds.amazonaws.com/master_stock
#spring.datasource.username=shri
#spring.datasource.password=oneplusone!
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
